export const Data = [
  {
    id: 1,
    name: 'Chicken Tenders',
    category: 'chicken',
    image: 'https://res.cloudinary.com/ehizeex-shop/image/upload/v1672322923/NetflixApp/chicken_tenders_quel6y.jpg',
    price: 280,
  },
  {
    id: 2,
    name: 'Roasted Chicken',
    category: 'chicken',
    image: 'https://res.cloudinary.com/ehizeex-shop/image/upload/v1672322922/NetflixApp/roast-chicken_nrc6r8.jpg',
    price: 300,
  },
  {
    id: 3,
    name: 'Wings',
    category: 'chicken',
    image: 'https://res.cloudinary.com/ehizeex-shop/image/upload/v1672322922/NetflixApp/chicken-wings_lv3zc9.jpg',
    price: 160,
  },
  {
    id: 4,
    name: 'Loaded Salad',
    category: 'salad',
    image: 'https://res.cloudinary.com/ehizeex-shop/image/upload/v1672323860/NetflixApp/loaded_salad_qq5jup.jpg',
    price: 135,
  },
  {
    id: 5,
    name: 'Ceasar Salad',
    category: 'salad',
    image: 'https://res.cloudinary.com/ehizeex-shop/image/upload/v1672323859/NetflixApp/caesar-salad-with-tuna-30216-1_noflfd.jpg',
    price: 140,
  },
  {
    id: 6,
    name: 'Kale Salad',
    category: 'salad',
    image: 'https://res.cloudinary.com/ehizeex-shop/image/upload/v1672323860/NetflixApp/kale_salad_ogune3.jpg',
    price: 130,
  },
  {
    id: 7,
    name: 'African Salad',
    category: 'salad',
    image: 'https://res.cloudinary.com/ehizeex-shop/image/upload/v1672323870/NetflixApp/African_Salad_s7vgxn.png',
    price: 100,
  },
  {
    id: 8,
    name: 'pepperoni pizza',
    category: 'pizza',
    image: 'https://res.cloudinary.com/ehizeex-shop/image/upload/v1672324456/NetflixApp/pepperoni_pizza_axwdat.jpg',
    price: 170,
  },
  {
    id: 9,
    name: 'Supreme Pizza',
    category: 'pizza',
    image: 'https://res.cloudinary.com/ehizeex-shop/image/upload/v1672324455/NetflixApp/Supreme_Pizza_jtvkj8.jpg',
    price: 240,
  },
  {
    id: 10,
    name: 'cheeseless pizza',
    category: 'pizza',
    image: 'https://res.cloudinary.com/ehizeex-shop/image/upload/v1672324456/NetflixApp/cheeseless_pizza_bkuecz.jpg',
    price: 190,
  },
  {
    id: 11,
    name: 'chinese pizza',
    category: 'pizza',
    image: 'https://res.cloudinary.com/ehizeex-shop/image/upload/v1672324456/NetflixApp/chinese_pizza_kgnbo1.jpg',
    price: 220,
  },
  {
    id: 12,
    name: 'chicken burger',
    category: 'chicken',
    image: 'https://res.cloudinary.com/ehizeex-shop/image/upload/v1672332323/NetflixApp/chiken_burger_ncsmeh.webp',
    price: 190,
  },
  {
    id: 13,
    name: 'jollof rice',
    category: 'chicken',
    image: 'https://res.cloudinary.com/ehizeex-shop/image/upload/v1672332323/NetflixApp/jollof_rice_gbzosf.webp',
    price: 180,
  },
  {
    id: 14,
    name: 'tilapia fish',
    category: 'fish',
    image: 'https://res.cloudinary.com/ehizeex-shop/image/upload/v1672331305/NetflixApp/tilapia_fish_g0ozkn.jpg',
    price: 300,
  },
  {
    id: 15,
    name: 'egg and plantain',
    category: 'meal',
    image: 'https://res.cloudinary.com/ehizeex-shop/image/upload/v1672331290/NetflixApp/edd_and_plantain_rey7l4.jpg',
    price: 120,
  },
  {
    id: 16,
    name: 'orange juice',
    category: 'beverage',
    image: 'https://res.cloudinary.com/ehizeex-shop/image/upload/v1672329938/NetflixApp/orangejuice_s4mdbi.webp',
    price: 60,
  },
  {
    id: 17,
    name: 'yogurt parfaite',
    category: 'dessert',
    image: 'https://res.cloudinary.com/ehizeex-shop/image/upload/v1672329944/NetflixApp/yogurt_parfait_kt8b5f.jpg',
    price: 150,
  },
  {
    id: 18,
    name: 'fruite juice',
    category: 'beverage',
    image: 'https://res.cloudinary.com/ehizeex-shop/image/upload/v1672329939/NetflixApp/fruite_juice_du7uqy.jpg',
    price: 90,
  },
  {
    id: 19,
    name: 'shawarma',
    category: 'chicken',
    image: 'https://res.cloudinary.com/ehizeex-shop/image/upload/v1672323737/NetflixApp/chiken_shawarma_c0ysna.jpg',
    price: 350,
  },
];
